### ISSUE TITLE
City of Aalen reports data breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#11851]
https://www.stuttgarter-zeitung.de/inhalt.unterschriftenliste-landet-beim-gegner-buerger-stehen-nach-datenpanne-im-regen.b416f0a1-1f67-4d9d-985f-015adf63fb27.html

**Comment by jasoncmiller79** [comment]
The city plays firm with data from critics
By Thomas Faltin July 20, 2018 - 18:22
The paper mill Palm in Aalen wants to expand, on the other hand resistance forms. Now the town hall unlawfully forwarded the names of 237 opponents to the company.

And the privacy? The paper maker Palm now knows which citizens see the expansion of the company critically. 

Aalen - The apology came promptly - but halfheartedly. Yes, Aalen's mayor, Thilo Rentschler, has now admitted that the city has forwarded personal data from 237 people who have signed a petition against the expansion of Palm Paper Mill in the Unterkochen district to the company and also to a planning office. "We very much regret this violation of the General Data Protection Regulation," says Rentschler. At the same time, however, he emphasizes that the construction process is carried out "in close coordination" with the paper mill, so that all statements would be discussed with those responsible, albeit anonymously. You have to read that way: the findings would have become known to the Papierfabrik Palm - and the public as well - anyway.

Not as bad as you might thought? The Citizens' Initiative Pro-Unterkochen (Pro-Uko) sees this quite differently. Many citizens would have trusted that their data would be treated confidentially, says one of the spokesman for Pro-Uko, Daniel Hellmann - actually only the administration and local council are allowed to see the addresses and names. Above all, there could be signatories who worked in the paper mill and now feared inconvenience. Incidentally, Hellmann does not consider it out of the question that the list in question also went to the Landratsamt and Regierungspräsidium.

The company boss is unusually well informed
And somehow with the findings from the list also made policy. Company boss Wolfgang Palm was quoted a few days ago in the "Aalener Nachrichten" with the words, no 200 of the signers came from Unterkochen, all others are from further afield. This statement made the Citizens' Initiative first to the fact that Palm had to be in possession of information, which he was not allowed to know from their point of view - after a request to the city, this acknowledged the data breach, but added that it was for the "personal concern "It is important to know the place of residence of the signatories. And, see above, such information will then be public. In fact, Wolfgang Palm also emphasizes to our newspaper that he does not draw his findings from the list. But where exactly, he did not want to answer, as well as the question of whether he let the illegally forwarded data deleted meanwhile.

Meanwhile, another statement Wolfgang Palms has become known - then most of the signers are not long-established, but moved in the last two years. So they do not speak for the undercooked. Daniel Hellmann is outraged: "It has to be asked if Palm continues to analyze its opponents on the basis of the unlawfully obtained data or if the town hall in Aalen continues to provide information about the initiators directly to the industrialist."


It is not yet clear what the consequences are
The consequences of the data breach for the city of Aalen is open. A spokesman for the State Data Protection Commissioner said that there are many indications that the city has acted unlawfully, but they will first ask for an opinion from Aalen. In principle, a fine could be imposed - and of course you could ask for the deletion of the data.

The cool reaction of the city and the pointed statements of CEO and citizens' initiative suggest that the relationship is shattered. The company can not understand how to oppose its project: it will invest half a billion euros in the then most modern paper mill in Europe. Unterkochen is the founding and headquarters of the company; Today it has 31 paper mills and corrugated board plants, 4,000 employees and an annual turnover of 1.5 billion euros. Conversely, the citizens' initiative is frustrated that you put them in the dirty corner. They are not against the enlargement at all, so Hellmann; but they wanted answers to many open questions - so there are significant gaps in sound insulation.

Now a conversation is scheduled for the 1st of August, in which, in addition to the city, District Administrator Klaus Pavel, representatives of the paper mill and Pro-Uko are to take part. Daniel Hellmann and his colleagues learned about the appointment from the newspaper. Whether they had time that day, no one asked them
