### ISSUE TITLE
New Mexico State Regulation and Licensing Hit by Data Breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#19235]
https://www.govtech.com/security/new-mexico-state-regulation-and-licensing-hit-by-data-breach

**Comment by etgifford** [comment]
New Mexico State Regulation and Licensing Department , HQ: Santa Fe, NAICS: 92926 (government), EMP: 14, discovered suspicious activity on their network Oct 7, 2022. Investigations show a data breach of 250,000 accounts exposed personal information: name, address, social security number, and “other identifying information”. The Department sent notice Dec 4, 2022. Since professional license numbers are public information, the state will not reissue licenses with new numbers. The department purchased a year of identity theft protection from Experian.

**Comment by alexcpsec** [comment]
Can't find any info about the substance of the attack, action, asset, etc. Marking as not eligible.
