### ISSUE TITLE
Data of 700,000 VodafoneZiggo customers exposed due to data breach - Blauw, Nebu

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#19665]
https://nltimes.nl/2023/03/29/data-700000-vodafoneziggo-customers-exposed-due-data-breach

**Comment by swidup** [comment]
Previously, the Dutch national railway, NS, warned that the personal data of approximately 780,000 customers [may have been involved in the same data breach](https://nltimes.nl/2023/03/28/dutch-railway-ns-warns-780000-customers-data-breach). https://nltimes.nl/2023/03/28/dutch-railway-ns-warns-780000-customers-data-breach

**Comment by swidup** [comment]
Netherlands Enterprise Agency, PME Pension Fund, USP  https://www.cpomagazine.com/cyber-security/data-breach-of-dutch-market-research-firms-impacts-millions-includes-some-income-information/

**Comment by etgifford** [comment]
JSON 28ce177c-f55f-43de-8e39-f761f4ac4432, VodafoneZiggo, HQ: Utrecht, Netherlands, Employees: 38, NAICS: 517000 (telecommunications). On March 10 and 11, 2023 the personal data of approximately 700,000 VodafoneZiggo customers leaked out due to a (supplier of a supplier) data breach of the market research firm Blauw. Blauw said the breach originated at market research software supplier Nebu, which provides research solutions to the business. (139+ organizations have reported the Nebu data breach to the Dutch Data Protection Authority). The stolen data was from customer satisfaction surveys sent out by Blauw, which it collects and processes for its clients. Compromised data includes: name, address, email, phone number, in some cases income information.

**Comment by alexcpsec-vz** [comment]
Added some flags in "attribute.Confidentiality" to make it clear it was Partner Data that was leaked.
