### ISSUE TITLE
US college cyberattack probe reveals 700K affected - Lansing Community College

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#19885]
https://cybernews.com/news/lansing-community-college-cyberattack/

**Comment by swidup** [comment]
https://www.lansingstatejournal.com/story/news/2023/11/13/data-breaches-lansing-community-college-lawsuits-court/71491333007/

**Comment by etgifford** [comment]
https://www.lcc.edu/alert.html  (June 29, 2023) Notice of Data Event
https://www.prnewswire.com/news-releases/console--associates-pc-lansing-community-college-data-breach-leaks-up-to-757k-social-security-numbers-301870793.html

**Comment by etgifford** [comment]
Lansing Community College, HQ: Lansing, Michigan, EMP: 1802, NAICS: 6113 (college, adult education) 757,832 student/alumni records breached: names, social security numbers. Breach occurred between Dec 22, 2022 – Mar 14, 2023, LCC became aware of suspicious activity on its network Mar 14, 2023, investigation completed May 24, 2023, notification Jun 29, 2023. Maine victims offered one year of ID theft protection and credit monitoring.

**Comment by swidup** [comment]
https://www.insidehighered.com/news/quick-takes/2024/10/17/lansing-community-college-settles-data-breach-suit

**Comment by etgifford** [comment]
In a class action lawsuit, LCC stated an “unauthorized actor” hacked the college’s internal computer systems and that “There is no evidence indicating that any personal identifiable information of the named plaintiffs, or any other persons, was exfiltrated from LCC’s computer networks,” the college said in court document. LCC further stated that it was “discontinuing the use of the vulnerable application attacked by the unauthorized actor,” increasing verification steps and digital surveillance of the college’s computer systems, and reducing the number of authorized administrators.

**Comment by etgifford** [comment]
JSON: d8c4f179-4324-4105-a210-f08a4ef8a6bf, Lansing Community College, HQ: Lansing, Michigan, EMP: 1802, NAICS: 6113 (college, adult education) 757,832 student/alumni records breached: names, social security numbers. Breach occurred between Dec 22, 2022 – Mar 14, 2023. LCC became aware of suspicious activity on its network Mar 14, 2023, investigation completed May 24, 2023, notification Jun 29, 2023. The breach compromised data from some people who haven't been affiliated with the college for decades.  Maine victims offered one year of ID theft protection and credit monitoring. Clop Ransomware Group (Russia) listed LCC as being a victim of it’s MOVEit attacks. In a class action lawsuit, LCC stated an “unauthorized actor” hacked the college’s internal computer systems and that “LCC has denied any significant damage, saying in court documents "there is no evidence indicating that any personal identifiable information of the named plaintiffs, or any other persons, was exfiltrated from LCC's computer networks" due to the breach and there also were no ransom demands nor any evidence that personal information from the college has been made available on the "dark web.". LCC further stated that it was “discontinuing the use of the vulnerable application attacked by the unauthorized actor,” increasing verification steps and digital surveillance of the college’s computer systems, and reducing the number of authorized administrators.

**Comment by alexcpsec-vz** [comment]
Since it was MOVEit, we can infer the next steps of the data exfil
