### ISSUE TITLE
Class-action lawsuit filed against Tampa General Hospital over data breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#19895]
https://www.wfla.com/news/hillsborough-county/class-action-lawsuit-filed-against-tampa-general-hospital-over-data-breach/

**Comment by swidup** [comment]
https://www.hipaajournal.com/tampa-general-hospital-sued-over-1-2-million-record-data-breach/

**Comment by etgifford** [comment]
https://www.infosecurity-magazine.com/news/tampa-hospital-data-breach/   article on the breach
https://www.wfla.com/news/hillsborough-county/1-2-million-affected-by-tampa-general-hospital-data-breach/   article on the breach

**Comment by etgifford** [comment]
Tampa General Hospital, HQ: Tampa Florida, EMP: 8207, NAICS: 62622 (Hospitals, clinics, healthcare). Data breach affecting 1,200,000 patient records. Detected unusual activity on computer systems May 31, 2023. Access occurred May 12, 2023. Notification Jul 19, 2023. Records contained: Names, address, date of birth, phone number, social security number, health insurance details, medical record numbers, patient account numbers, dates of service, and limited treatment information. Attempted ransomware execution was prevented due to “monitoring systems and skilled technology professionals”.

**Comment by swidup** [comment]
Moving this into Issue 20811.  Also coding it into HHS subset.
