### ISSUE TITLE
ALPHV ransomware gang claims attack on Florida circuit court

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#19979]
https://www.bleepingcomputer.com/news/security/alphv-ransomware-gang-claims-attack-on-florida-circuit-court/

**Comment by etgifford** [comment]
https://2ndcircuit.leoncountyfl.gov/securityNotice.php

**Comment by etgifford** [comment]
https://www.floridabar.org/the-florida-bar-news/chief-judge-john-miller-details-the-first-circuits-massive-cyberattack/

**Comment by etgifford** [comment]
Florida Circuit Court, Pensacola, FL, Public Administration NAICS 922110 (part of the First Judicial Circuit, Northwest Florida: Escambia, Okaloosa, Santa Rosa, and Walton Counties, 25 employees, United States. Ransomware attack by ALPHV (BlackCat) posted breached data information on their website, claiming to have two terabytes of files. Acquired SSNs, Taxpayer identification number, date of birth, driver’s license information, state identification number, health and insurance information, tax returns, and CVs of employees, including judges, network map of court systems, complete with local and remote service creds. ALPHV was able to get into the backup system since “it was connected to the main system”. Breach discovered Sep 29, 2023, hired Mandiant to investigate. Court found out about the compromised data after an employee found their own PII on the darkweb. A circuit court judge, Judge miller, stated lawyers should train their office personnel to identify suspicious emails.

**Comment by alexcpsec-vz** [comment]
First action, unknown. Needed to add Ransomware as the follow up action
