### ISSUE TITLE
Turkey: KVKK announces Vava Cars data breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20111]
https://www.dataguidance.com/news/turkey-kvkk-announces-vava-cars-data-breach

**Comment by etgifford** [comment]
https://sorhanlawconsultancy.com.tr/language/en/data-breach-notifications-2/

**Comment by etgifford** [comment]
JSON 9d459f49-2990-4f56-8054-99fc322d5f0b, Vava Cars, HQ: Istanbul, Turkey, EMP: 314, NAICS: 441100 (Automobile Dealers). The data breach was conducted and discovered on Oct 31, 2023. The cause is an internal user's credentials being compromised and used to access application data. Reported Nov 9, 2023. 32,589 people were affected, including employees and customers. Data included: name, address, telephone number, email, IBAN, bank details, price, VIN, license plate number and vehicle information.
