### ISSUE TITLE
Poloniex Loses 577 Billion SHIB To Security Breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20121]
https://timestabloid.com/poloniex-loses-577-billion-shib-to-security-breach/

**Comment by etgifford** [comment]
https://www.bitdefender.com/blog/hotforsecurity/poloniex-hackers-have-begun-to-move-some-of-the-stolen-120-million/
https://www.halborn.com/blog/post/explained-the-poloniex-hack-november-2023
https://cybernews.com/crypto/crypto-exchange-poloniex-hacked-offers-bounty/
https://olympixai.medium.com/poloniex-cryptocurrency-exchange-hack-analysis-711dc845519d
https://support.poloniex.com/hc/en-us/articles/23932603838871-Security-Alert-Regarding-Exchange-Accounts-Amid-Rising-Cyber-Treats

**Comment by etgifford** [comment]
JSON 12ce193d-52fe-4ce5-82e8-0d21c2830ade, Poloniex, HQ: Boston, MA, EMP: 151, NAICS: 523210 (Securities and Commodity Exchanges). In November 10, 2023, the Poloniex cryptocurrency exchange suffered a hack due to compromised private keys. It is believed that the hackers gained unauthorized access to Poloniex’s systems and found hot wallet private keys stored in the internal systems. Once inside, they escalated their privileges and breached the hot wallets, siphoning off a substantial amount of cryptocurrency. Poloniex publicly acknowledged the hack 15 min after it was discovered by blockchain security firms PeckShield and Cyvers, which noticed multiple suspicious transactions from Poloniex’s hot wallet. The attackers, “Lazarus Group” (associated with the government of North Korea) drained an estimated $126 million from the project’s hot wallets. This attack was made possible by blockchain wallets controlled by a single private key. On May 9, 2024, hackers started to attempt to move funds stolen. Poloneix’s site stresses not installing untrusted third-party applications, plugins and browser extensions numerous times. This is the possible vector “Lazarus Group” used to gain access.
