### ISSUE TITLE
Pierce College cyberattack exposed 155,000 people’s data. Is the district at fault?

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20131]
https://www.thenewstribune.com/news/local/article281698368.html

"“Upon learning of this activity, Pierce took steps to secure its network and commenced an investigation,” the district’s legal counsel, Benjamin Wanger, wrote in a letter to the state agency. “The investigation found evidence of unauthorized access to Pierce’s network between July 23, 2023 and July 24, 2023, during which time certain files contained on Pierce’s servers were acquired by unauthorized actors.”"

**Comment by swidup** [comment]
https://www.thenewstribune.com/news/local/education/article277891968.html

**Comment by etgifford** [comment]
https://www.govtech.com/education/higher-ed/pierce-college-sued-in-wake-of-cyber-attack,
https://www.breachsense.com/breaches/pierce-college-data-breach/
https://agportal-s3bucket.s3.amazonaws.com/databreach/BreachA26784.pdf

**Comment by etgifford** [comment]
JSON fa5b3a8d-a4fb-4e51-a6a1-8cf5d7f245d2, Pierce College, HQ: Puyallup, WA, EMP: 648, NAICS: 611310 (Colleges, Universities, and Professional Schools). July 24, 2023 Pierce identified suspicious activity in its network. Investigation showed breach occurred July 23, 2023. Investigation concluded Sept 8, 2023. An employee fell victim to a phish and downloaded a file.“ “As always, it is preferable to view in your browser rather than download the file,” the school said.” “Rhysida Gang” posted the data of 155,811 students and staff on a dark web auction page: SSN, name, address, driver’s license, financial and banking information, date of birth. Letters sent to students and staff affected on Oct 16, 2023, offered one year Fraud/ID theft monitoring from Experian. A lawsuit was filed in Nov 2023. Victims have experienced ID theft, ta fraud, unauthorized lines of credit opened in their names, medical and healthcare fraud, and unauthorized access to their bank accounts.
